---
# tasks file for nginx
- name: install nginx
  yum: name={{item}} state=present
  with_items:
  - nginx
  - firewalld

- name: copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: start firewalld
  service: name=firewalld state=started

- name: insert firewalld rule for nginx
  firewalld: port={{nginx_port}}/tcp permanent=true state=enabled immediate=yes

- name: start nginx
  service: name=nginx state=started enabled=yes
